# Default values for rundeck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 887254321648.dkr.ecr.ap-southeast-3.amazonaws.com/rundeck
  tag: v3
  pullPolicy: IfNotPresent
  pullSecrets: "regcred"

deployment:
  replicaCount: 1
  annotations: {}
  strategy:
    type: RollingUpdate
    # Recreate can help when using persistent volumes
    # type: Recreate

rundeck:
  adminUser: "admin:admin,user,admin,architect,deploy,build"
  realmProperties: |
    admin:admin,user,admin,architect,deploy,build
    user:admin,user,deploy,build
    deploy:deploy,build
    build:build
  env:
    RUNDECK_GRAILS_URL: "https://rundeck.example.com"
    RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
    RUNDECK_DATABASE_USERNAME: rundeck
    RUNDECK_DATABASE_PASSWORD: rundeck
    RUNDECK_DATABASE_URL: jdbc:mariadb://xxx.xxx.xxx:3306/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    RUNDECK_SERVER_FORWARDED: "true"
    RUNDECK_PREAUTH_ENABLED: "true"
    RUNDECK_PREAUTH_ATTRIBUTE_NAME: REMOTE_USER_GROUPS
    RUNDECK_PREAUTH_DELIMITER: ","
    RUNDECK_PREAUTH_USERNAME_HEADER: X-Forwarded-User-Email
    RUNDECK_PREAUTH_ROLES_HEADER: X-Forwarded-Roles
    RUNDECK_PREAUTH_REDIRECT_LOGOUT: "true"
    RUNDECK_PREAUTH_USERSYNC_ENABLED: "true"
    RUNDECK_PREAUTH_USERSYNC_EMAIL: "X-Forwarded-User-Email"
    RUNDECK_SECURITY_HTTPHEADERS_PROVIDER_CSP_ENABLED: "false"
    # RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME: com.rundeck.rundeckpro.amazon-s3
    # RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET: ${RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET}
    # RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION: ${RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION}
    # RUNDECK_STORAGE_CONVERTER_1_CONFIG_PASSWORD: ${RUNDECK_STORAGE_PASSWORD}
    # RUNDECK_CONFIG_STORAGE_CONVERTER_1_CONFIG_PASSWORD: ${RUNDECK_STORAGE_PASSWORD}
    # RUNDECK_TOKENS_FILE: /home/rundeck/extra/tokens.properties

  # Name of the secret containing SSH files to mount under ~/.ssh
  # sshSecrets: "ssh-secret"

  # Name of secret containing to mount under ~/.aws/
  # awsConfigSecret: "aws-secret"

  # Name of secret to mount under ~/.kube/
  # kubeConfigSecret: "kube-secret"

  # Name of secret containing additional sensitive Runtime environment variables (eg: RUNDECK_DATABASE_PASSWORD)
  # See https://hub.docker.com/r/rundeck/rundeck/
  # envSecret: "env-secret"

  # Name of secret containing additional files to mount into Rundeck's ~/extra directory.
  # This can be useful for populating a file you reference with RUNDECK_TOKENS_FILE above.
  # extraConfigSecret: "extra-secret"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  # Set existingClaim to the name of an existing PVC to reuse a volume managed outside this helm chart
  # existingClaim:
  # If deployed on AWS you can optionally specify an existing EBS volume by ID
  # awsVolumeId:

  # Set claim.create:true  to have the helm chart manage the creation of a new PVC for this deployment
  claim:
    create: true
    storageClass:
    accessMode: ReadWriteOnce
    size: 10G

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  annotations: {}
    # AWS IRSA annotation
    # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/rundeck
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
    nginx.ingress.kubernetes.io/auth-snippet: |
      # Skip oauth if a rundeck token header is present (rundeck-cli)
      if ($http_x_rundeck_auth_token) {
        return 200;
      }
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Set auth from oauth2-proxy request
      auth_request_set $x_auth_user $upstream_http_x_auth_request_user;
      auth_request_set $x_auth_email $upstream_http_x_auth_request_email;

      # Add auth headers to proxy_pass request so rundeck can use them
      proxy_set_header X-Forwarded-User $x_auth_user;
      proxy_set_header X-Forwarded-User-Email $x_auth_email;

      # Lua block to manage rundeck group mapping and modify request headers
      access_by_lua_block {
        -- Lua table for rundeck user/group mapping, kinda like realm.properties
        local users = {
          ["user1"] = "admin,user",
          ["user2"] = "user,user"
        }

        -- If auth user is set, lookup group table and add group header to proxy_pass
        if users[ngx.var.x_auth_user] ~= nil then
          ngx.req.set_header("X-Forwarded-Roles", users[ngx.var.x_auth_user])
        end

        -- Remove any forwarded headers if tokens are used
        if ngx.header['X-Rundeck-Auth-Token'] ~= nil then
          ngx.req.clear_header("X-Forwarded-User")
          ngx.req.clear_header("X-Forwarded-Roles")
          ngx.req.clear_header("X-Forwarded-User-Email")
        end
      }
  hosts:
    - host: rundeck.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: rundeck-tls
      hosts:
        - rundeck.example.com

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1200m
  #   memory: 1400Mi
  # requests:
  #   cpu: 600m
  #   memory: 700Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Replace the nginx.conf file in this chart with a customised config.
nginxConfOverride:
  # # This example adds configuration for external auth e.g. via oauth2-proxy
  # # It also demonstrates templating in another arbitrary value (authRoles)
  # # to create a map of external users to rundeck roles
  # events {
  #   worker_connections  1024;
  # }
  # http {
  #   map $http_x_forwarded_user $x_forwarded_roles {
  # {{- .Values.authRoles | nindent 4 }}
  #   }
  #   server {
  #     location /metrics/ {
  #       proxy_pass http://localhost:4440;
  #       proxy_set_header Host $http_host;
  #       proxy_set_header X-Forwarded-User metrics;
  #       proxy_set_header X-Forwarded-Roles user;
  #     }
  #     location / {
  #       recursive_error_pages on;
  #       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #       proxy_set_header X-Forwarded-Proto $scheme;
  #       proxy_set_header X-Forwarded-Roles $x_forwarded_roles;
  #       proxy_set_header User-Agent $http_user_agent;
  #       proxy_pass http://localhost:4440;
  #     }
  #   }
  # }

# volumes made available to all containers.
volumes:
  - name: plugins
    emptyDir: {}

# volumeMounts to add to the rundeck container and configurable paths
volumeMounts:
  - name: data
    mountPath: /home/rundeck/server/data

# initContainers can be used to download plugins or customise your rundeck installation
initContainers: []
  # - name: download-plugins
  #   image: alpine:3.8
  #   command: [sh, -c]
  #   args:
  #     - wget https://github.com/rundeck-plugins/kubernetes/releases/download/2.0.13/kubernetes-2.0.13.zip -O /home/rundeck/libext/kubernetes-2.0.13.zip
  #   volumeMounts:
  #     - mountPath: /home/rundeck/libext/
  #       name: plugins

# sideCars can run additional containers in the pod
sideCars: ""
  # - name: cloudsql-proxy
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.17
  #   command:
  #     - "/cloud_sql_proxy"
  #     - "-instances=<instance_end_point>=tcp:3306"
  #   securityContext:
  #     runAsNonRoot: true
